import sys
import argparse
import time
import textwrap
from typing import Dict, Tuple, Any, Optional, Final, List
from dataclasses import dataclass
from types import MappingProxyType

# ANSI Colors for help output
C_CYAN = "\033[96m"
C_YELLOW = "\033[93m"
C_GREEN = "\033[92m"
C_RED = "\033[91m"
C_MAGENTA = "\033[95m"
C_BOLD = "\033[1m"
C_RESET = "\033[0m"

# STRING RESOURCES
@dataclass(frozen=True)
class StringResources:
    @dataclass(frozen=True)
    class UI:
        APP_DESC: str = f"{C_CYAN}CS2 Frame Analysis Utility for `cl_showfps 4` logs{C_RESET}"
        MSG_ANALYZING: str = f"\n{C_CYAN}Analyzing performance schema...{C_RESET}"
        MSG_MISSING_DEPS: str = f"\n{C_RED}[!] Missing required packages: {{pkg_list}}{C_RESET}"
        MSG_INSTALL: str = "Please install them to run the analysis:"
        MSG_PIP: str = f"{C_GREEN}pip install {{pkg_list}}{C_RESET}\n"
        MSG_LOAD_ERR: str = f"{C_RED}Data Load Error: {{error}}{C_RESET}"
        MSG_NO_DATA: str = "No valid numerical data found in CSV."

    @dataclass(frozen=True)
    class Section:
        LINE: str = "=" * 50
        TITLE: str = "  CS2 PERFORMANCE PROFILE | {duration:.2f}s"
        ENGINE: str = "Engine & Network"
        GLOSSARY: str = f"\n{C_CYAN}{C_BOLD}--- METRICS GLOSSARY ---{C_RESET}"

    @dataclass(frozen=True)
    class Metric:
        LBL_MEAN: str = "Mean"
        LBL_MAX: str = "Max"
        LBL_MIN: str = "Min"
        LBL_MEDIAN: str = "Median"
        LBL_JITTER: str = "Std Dev (Jitter)"
        LBL_SERVER: str = "Avg Server Delta"
        LBL_STUTTER: str = "Stutters (>{threshold}ms)"
        SUFFIX_LOW: str = "Low"
        SUFFIX_HIGH: str = "High"
        UNIT_MS: str = "ms"
        UNIT_FPS: str = "FPS"

    # Using textwrap.dedent for clean, readable multi-line strings
    HELP_EPILOG: str = textwrap.dedent(f"""
        {C_GREEN}{C_BOLD}Requirements:{C_RESET}
          Python 3.7+
          Packages: pandas, numpy, tqdm, colorama
          Install via: {C_YELLOW}pip install pandas numpy tqdm colorama{C_RESET}

        {C_RED}{C_BOLD}Disclaimer:{C_RESET}
          This script parses CSV logs specifically generated by the {C_YELLOW}`cl_showfps 4`{C_RESET} 
          command in Counter-Strike 2. Please note that {C_YELLOW}`cl_showfps 4`{C_RESET} is a heavy 
          profiling tool. On low-spec systems, the overhead of logging data every 
          frame can cause a noticeable drop in your actual game performance.

        {C_MAGENTA}{C_BOLD}Usage Examples:{C_RESET}
          python analyze_cs2.py match_log.csv
          python analyze_cs2.py match_log.csv --brief
    """)

    GLOSSARY_MAP: MappingProxyType = MappingProxyType({
        "Frame FPS": "Instantaneous speed. Best for finding stutters.",
        "Smooth FPS": "Trailing average. This is what you see in the HUD.",
        "Frame MS": "Time to render one frame (ms). Lower is better.",
        "Server Frame MS": "Server tick processing time. High = Server Lag.",
        "Median": "The middle performance value (50th percentile).",
        "1% Low": "Performance at the 1st percentile. Fluidity check.",
        "0.1% Low": "Absolute worst hitches (e.g., teleports/crashes).",
        "Std Dev (Jitter)": "Consistency check. High = 'Micro-stutter'.",
    })

# BEHAVIORAL CONFIGURATION
@dataclass(frozen=True)
class Config:
    PERCENTILE_MAP: Final[MappingProxyType] = MappingProxyType({
        0.5:   "Median",
        0.1:   "10%",
        0.01:  "1%",
        0.001: "0.1%"
    })
    STUTTER_THRESHOLD_MS: float = 50.0
    COL_TIME: str = 'Time'
    COL_FRAME_FPS: str = 'Frame FPS'
    COL_SMOOTH_FPS: str = 'Smooth FPS'
    COL_FRAME_MS: str = 'Frame MS'
    COL_SMOOTH_MS: str = 'Smooth MS'
    COL_SERVER_MS: str = 'Server Frame MS'

STR = StringResources()
CFG = Config()

# DEPENDENCY VALIDATOR
def validate_dependencies() -> None:
    required = ['pandas', 'numpy', 'tqdm', 'colorama']
    missing = [pkg for pkg in required if not __import__('importlib').util.find_spec(pkg)]
    if missing:
        pkgs = ", ".join(missing)
        print(STR.UI.MSG_MISSING_DEPS.format(pkg_list=pkgs))
        print(STR.UI.MSG_INSTALL)
        print(STR.UI.MSG_PIP.format(pkg_list=pkgs))
        sys.exit(1)

# HELPERS
def show_help_glossary() -> None:
    print(STR.Section.GLOSSARY)
    for k, v in STR.GLOSSARY_MAP.items():
        print(f"{C_YELLOW}{k:18}{C_RESET}: {v}")
    print("-" * 50)

# CORE ANALYZER CLASS
class CS2Analyzer:
    def __init__(self, file_path: str) -> None:
        self.file_path: str = file_path
        self.df: Optional[Any] = None 
        self.results: Dict[str, Dict[str, float]] = {}
        self.duration: float = 0.0
        self.server_diff: float = 0.0
        self.stutter_count: int = 0
        self.stutter_rate: float = 0.0

    def load_data(self) -> None:
        import pandas as pd
        try:
            self.df = pd.read_csv(self.file_path, skipinitialspace=True, engine='python')
            self.df.columns = self.df.columns.str.strip()
            
            numeric_cols = [CFG.COL_FRAME_FPS, CFG.COL_SMOOTH_FPS, CFG.COL_FRAME_MS, 
                            CFG.COL_SMOOTH_MS, CFG.COL_SERVER_MS, CFG.COL_TIME]

            for col in numeric_cols:
                if col in self.df.columns:
                    self.df[col] = pd.to_numeric(self.df[col], errors='coerce')

            self.df.dropna(subset=[CFG.COL_FRAME_MS], inplace=True)
            if self.df.empty:
                raise ValueError(STR.UI.MSG_NO_DATA)
        except Exception as e:
            print(STR.UI.MSG_LOAD_ERR.format(error=str(e)))
            sys.exit(1)

    def _calculate_metrics(self, series: Any, reverse: bool = False) -> Dict[str, float]:
        import pandas as pd
        stats: Dict[str, float] = {
            STR.Metric.LBL_MEAN: float(series.mean()),
            STR.Metric.LBL_MAX: float(series.max()),
            STR.Metric.LBL_MIN: float(series.min()),
            STR.Metric.LBL_JITTER: float(series.std()),
        }
        for p, base_label in CFG.PERCENTILE_MAP.items():
            label = STR.Metric.LBL_MEDIAN if p == 0.5 else f"{base_label} {STR.Metric.SUFFIX_LOW if reverse else STR.Metric.SUFFIX_HIGH}"
            val = series.quantile(p) if reverse else series.quantile(1-p)
            stats[label] = float(val) if pd.notnull(val) else 0.0
        return stats

    def run_analysis(self) -> None:
        from tqdm import tqdm
        tasks = [(CFG.COL_FRAME_FPS, True), (CFG.COL_SMOOTH_FPS, True),
                 (CFG.COL_FRAME_MS, False), (CFG.COL_SMOOTH_MS, False)]

        print(STR.UI.MSG_ANALYZING)
        for col, rev in tqdm(tasks, bar_format="{l_bar}%s{bar}%s{r_bar}" % (C_GREEN, C_RESET)):
            time.sleep(0.05) 
            self.results[col] = self._calculate_metrics(self.df[col], reverse=rev)

        self.duration = float(self.df[CFG.COL_TIME].iloc[-1] - self.df[CFG.COL_TIME].iloc[0])
        self.server_diff = float((self.df[CFG.COL_SERVER_MS] - self.df[CFG.COL_FRAME_MS]).mean())
        self.stutter_count = int((self.df[CFG.COL_FRAME_MS] > CFG.STUTTER_THRESHOLD_MS).sum())
        self.stutter_rate = (self.stutter_count / len(self.df)) * 100

    def display_report(self) -> None:
        from colorama import Fore, Style
        print(f"\n{Fore.MAGENTA}{Style.BRIGHT}{STR.Section.LINE}")
        print(f"{Fore.MAGENTA}{Style.BRIGHT}{STR.Section.TITLE.format(duration=self.duration)}")
        print(f"{Fore.MAGENTA}{Style.BRIGHT}{STR.Section.LINE}{Style.RESET_ALL}")

        for category, metrics in self.results.items():
            print(f"\n{Fore.CYAN}{Style.BRIGHT}[{category}]{Style.RESET_ALL}")
            unit = STR.Metric.UNIT_MS if "MS" in category else STR.Metric.UNIT_FPS
            for label, val in metrics.items():
                color = Fore.WHITE
                if label in (STR.Metric.LBL_MEAN, STR.Metric.LBL_MEDIAN): color = Fore.GREEN
                elif STR.Metric.SUFFIX_LOW in label or STR.Metric.SUFFIX_HIGH in label: color = Fore.YELLOW
                elif label == STR.Metric.LBL_JITTER: color = Fore.RED if val > 10 else Fore.GREEN
                print(f"  {color}{label:20}: {val:8.2f} {unit}{Style.RESET_ALL}")

        stutter_color = Fore.RED if self.stutter_count > 0 else Fore.GREEN
        print(f"\n{Fore.CYAN}{Style.BRIGHT}[{STR.Section.ENGINE}]{Style.RESET_ALL}")
        print(f"  {Fore.WHITE}{STR.Metric.LBL_SERVER:20}: {self.server_diff:.2f} {STR.Metric.UNIT_MS}")
        stutter_lbl = STR.Metric.LBL_STUTTER.format(threshold=CFG.STUTTER_THRESHOLD_MS)
        print(f"  {stutter_color}{stutter_lbl:20}: {self.stutter_count} ({self.stutter_rate:.2f}%){Style.RESET_ALL}")
        print(f"{Fore.MAGENTA}{Style.BRIGHT}{STR.Section.LINE}{Style.RESET_ALL}\n")

# EXECUTION
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=STR.UI.APP_DESC,
        epilog=STR.HELP_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("file", nargs='?', help="Path to your profiling CSV")
    parser.add_argument("-b", "--brief", action="store_true", help="Omit the metrics glossary from output")
    
    args = parser.parse_args()
    if not args.file:
        parser.print_help()
        sys.exit(0)
    if not args.brief:
        show_help_glossary()
        
    validate_dependencies()
    from colorama import init
    init(autoreset=True)

    engine = CS2Analyzer(args.file)
    engine.load_data()
    engine.run_analysis()
    engine.display_report()