"""
CS2 Frame Analysis Utility for `cl_showfps 4` logs.

This module provides a command-line interface to analyze performance logs
generated by the Counter-Strike 2 engine, helping identify frame timing
issues and hardware bottlenecks.
"""

import sys
import argparse
import colorama
from src.core.strings import STRINGS as STR
from src.core.utils import validate_dependencies, show_help_glossary
from src.core.cs_prof_analyzer import CsProfAnalyzer


def main() -> None:
    """Entry point for the CS2 Performance Analysis utility."""
    parser = argparse.ArgumentParser(
        description=STR.APP_DESC,
        epilog=STR.HELP_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("file", nargs="?", help="Path to your profiling CSV")
    parser.add_argument(
        "-b", "--brief", action="store_true", help="Omit the metrics glossary from output"
    )

    args = parser.parse_args()

    if not args.file:
        parser.print_help()
        sys.exit(0)

    if not args.brief:
        show_help_glossary()

    validate_dependencies()

    colorama.init(autoreset=True)

    engine = CsProfAnalyzer(args.file)
    engine.load_data()
    engine.run_analysis()
    engine.display_report()


if __name__ == "__main__":
    main()
