name: CI / Quality Check

on:
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check version change
        run: |
          base_branch=$(git branch -r | grep -E 'origin/(master|main)$' | head -n 1)
          files=$(git diff --name-only $base_branch...HEAD)
          relevant_files=""
          for f in $files; do
            if ! python build_utils/ci_cd_utils.py check "$f"; then
              relevant_files="$relevant_files $f"
            fi
          done

          if [ -n "$relevant_files" ]; then
            echo "The following files triggered the version bump requirement:"
            echo "$relevant_files"

            git show $base_branch:src/core/__version__.py > old_version.py

            # Check if version incremented (handle potential path changes)
            if python build_utils/ci_cd_utils.py old_version.py src/core/__version__.py; then
              echo "Version incremented successfully."
            else
              echo "Error: src/core/__version__.py must be incremented."
              exit 1
            fi
          else
            echo "No relevant changes detected, skipping version validation."
          fi


  validate-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r build_utils/requirements/lint.txt
      - name: Run Pylint
        run: true

  validate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install -r build_utils/requirements/test.txt
      - name: Run Tests
        run: pytest
